# Generated by Django 3.2.16 on 2022-10-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rated',
        ),
    ]
