# Generated by Django 3.2.16 on 2022-10-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_remove_rating_rated'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('owner', 'petsitting'), name='unique_rating'),
        ),
    ]
