# Generated by Django 3.2.16 on 2022-10-22 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('compensation', models.CharField(max_length=130)),
                ('location', models.CharField(max_length=150)),
                ('status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Ongoing'), (3, 'Finished')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pets', models.ManyToManyField(blank=True, to='pets.Pet')),
            ],
            options={
                'ordering': ['-date_from', '-created_at'],
            },
        ),
    ]
