# Generated by Django 3.2.16 on 2022-10-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='pets',
            field=models.ManyToManyField(blank=True, related_query_name='pets', to='pets.Pet'),
        ),
    ]
