# Generated by Django 3.2.16 on 2022-10-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='pets',
        ),
        migrations.AddField(
            model_name='ad',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Pet-sitting'), (1, 'Pet-sitter'), (2, 'Unspecified')], default=2),
        ),
    ]
