# Generated by Django 3.2.16 on 2022-10-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_owner'),
        ('ads', '0004_alter_ad_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='pets',
            field=models.ManyToManyField(blank=True, related_name='pet_in_ad', to='pets.Pet'),
        ),
    ]
