# Generated by Django 3.2.16 on 2022-10-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20221023_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='pets',
            field=models.SmallIntegerField(choices=[(1, 'Cat'), (2, 'Dog'), (3, 'Bird'), (4, 'Horse'), (5, 'Wild animal'), (6, 'Exotic animal'), (7, 'Mammal'), (8, 'Fish'), (9, 'Reptile'), (10, 'Insect'), (11, 'Other'), (12, 'Unspecified')], default=12),
        ),
    ]
