# Generated by Django 3.2.16 on 2022-10-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_ad_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='pets',
            field=models.CharField(choices=[('C', 'Cat'), ('D', 'Dog'), ('B', 'Bird'), ('H', 'Horse'), ('W', 'Wild animal'), ('E', 'Exotic animal'), ('M', 'Mammal'), ('F', 'Fish'), ('R', 'Reptile'), ('I', 'Insect'), ('O', 'Other'), ('U', 'Unspecified')], default='U', max_length=20),
        ),
    ]
