# Generated by Django 3.2.16 on 2022-10-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_ad_pets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['date_from', '-created_at']},
        ),
    ]
