# Generated by Django 3.2.16 on 2022-11-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_ad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Active'), (3, 'Finished')], default=0),
        ),
    ]
