# Generated by Django 3.2.16 on 2022-11-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_ad_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ad',
            name='pets',
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Finished')], default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='pets',
            field=models.ManyToManyField(related_name='ad', to='ads.PetChoice'),
        ),
    ]
