# Generated by Django 3.2.16 on 2022-11-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_auto_20221114_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='pets',
            field=models.ManyToManyField(blank=True, related_name='ad', to='ads.PetChoice'),
        ),
    ]
