# Generated by Django 3.2.16 on 2022-10-26 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_alter_pet_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetSitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('compensation', models.CharField(max_length=130)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('status', models.SmallIntegerField(choices=[(0, 'Planned'), (1, 'Ongoing'), (2, 'Finished')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitting_owner', to=settings.AUTH_USER_MODEL)),
                ('pets', models.ManyToManyField(blank=True, related_name='pets_to_sit', to='pets.Pet')),
                ('petsitter', models.ForeignKey(on_delete=models.SET('deleted'), related_name='petsitter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'date_from', '-created_at'],
            },
        ),
    ]
