# Generated by Django 3.2.16 on 2022-10-28 09:24

from django.conf import settings
from django.db import migrations, models
import pet_sittings.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet_sittings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitting',
            name='petsitter',
            field=models.ForeignKey(on_delete=models.SET(pet_sittings.models.get_deleted_user), related_name='petsitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
