# Generated by Django 3.2.16 on 2022-10-24 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=90)),
                ('content', models.TextField(blank=True)),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reciver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent'],
            },
        ),
    ]
